### ISSUE TITLE
Norton Security deleted the main executable

### ISSUE THREAD

**Issue by stysan** [virejdasani/Fruit-Ninjimmy#1]
### Yo, what's this?
So I was just browsing around GitHub and noticed [this (Fruit Ninjimmy)](https://github.com/virejdasani/Fruit-Ninjimmy/).  
### Oh, looks like a cool game
I was curious what this is because I didn't watch your YouTube channel for a while and tried downloading this.
I unpacked the game and clicked on the executable.
### Norton be like:
When I double-clicked on it I've been welcomed with an error.  
Only one _yo man no access go away_ required for me to understand: it fricked up.
### What Norton did?
It is deleting all the games .dll files at the moment. Already deleted. And deleted all games executables. And I don't even know what the hell is wrong here! Please reply :/

_Edit: Norton gave me WS.Reputation.1 so this is your side: send it to Symantec to make it undetected. Thank you._

**Comment by virejdasani** [comment]
Hmm, I'm not very familiar with Norton but I think this might help:
https://superuser.com/questions/1137080/prevent-norton-from-deleting-downloaded-files
Let me know if this works out for you, thanks!

**Comment by stysan** [comment]
> Hmm, I'm not very familiar with Norton but I think this might help: https://superuser.com/questions/1137080/prevent-norton-from-deleting-downloaded-files Let me know if this works out for you, thanks!

Ok, I'll try it out.
